package com.proyecto.aquamaris.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class DBHelper extends SQLiteOpenHelper {

    private static final int DATABASE_VERSION = 1;
    private static final String DATABASE_NAME = "TablaAquaMaris.sql";
    public static final String TABLA = "peces";


    public DBHelper(@Nullable Context context) {
        super(context, "TablaAquaMaris.db", null, 1);
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        sqLiteDatabase.execSQL("CREATE TABLE "+TABLA+"("+
                "pais TEXT NOT NULL,"+
                "nombre_cientifico TEXT NOT NULL,"+
                "familia TEXT NOT NULL,"+
                "localizacion TEXT NOT NULL,"+
                "provincias TEXT NOT NULL)");

        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Monacanthus hispidus','Monacanthidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagrus pagrus','Sparidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplodus vulgaris','Sparidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachinus draco','Trachinidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Serranus atricauda','Serranidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scorpaena teneriffea','Scorpaenidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus bogaraveo','Sparidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Box boops','Sparidae','Islas Canarias','El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Epinephelus gigas','Serranidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Muraena augusti','Muraenidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Mullus surmuletus','Mullidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Belone belone','Belonidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Synodus saurus','Synodontidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pseudocaranx dentex','Carangidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sparisoma rubripinne','Scaridae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Centrolabrus trutta','Labridae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Serranus scriba','Serranidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lichia glauca','Carangidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Thalassoma pavo','Labridae','Islas Canarias','El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Microchirus ocellatus','Soleidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lithognathus mormyrus','Sparidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Blennius canariensis','Blenniidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Liza aurata','Mugilidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Platophrys podas','Bothidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Labrisomus nuchipinnis','Labrisomidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scorpaena rubellio','Scorpaenidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sphoeroides spengleri','Tetraodontidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Chelidonichthys lucerna','Triglidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gobius maderensis','Gobiidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sparisoma cretense','Scaridae','Islas Canarias','El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepidopus caudatus','Trichiuridae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Apterichtus anguiformis','Ophichthidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Macroramphosus scolopax','Centriscidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Macroramphosus gracilis','Centriscidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Malacocephalus occidentalis','Macrouridae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Raja clavata','Rajidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Ruvettus pretiosus','Gempylidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus centrodontus','Sparidae','Islas Canarias','El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Carangidae','Carangidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scorpaena ustulata','Scorpaenidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sphyraena sphyraena','Sphyraenidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trigla lineata','Triglidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Muraena melanotis','Muraenidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scomber japonicus','Scombridae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Centrophorus lusitanicus','Centrophoridae','Islas Canarias','El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Dasyatis pastinaca','Dasyatidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplodus sargus','Sparidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachurus mediterraneus','Carangidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepidaplois scrofa','Labridae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Conger conger','Congridae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sparus pagrus','Sparidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bramidae','Bramidae','Islas Canarias','El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Muraena','Muraenidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Caranx dentex','Carangidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lycodontis unicolor','Muraenidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Solea lascaris','Soleidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus erythrinus','Sparidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Umbrina valida','Sciaenidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Spondyliosoma cantharus','Sparidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Promethichthys prometheus','Gempylidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Mugil auratus','Mugilidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Muraena helena','Muraenidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Mustelus mustelus','Triakidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lycodontis vicinus','Muraenidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scomber colias','Scombridae','Islas Canarias','El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pricanthidae','Priacanthidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Priacanthus fulgens','Priacanthidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachurus trachurus','Carangidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Dentex macrophthalmus','Sparidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus acarne','Sparidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Serranus cabrilla','Serranidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplecogaster bimaculata pectoralis','Gobiesocidae','Islas Canarias','El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepadogaster webbianus','Gobiesocidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Benthosema suborbitale','Myctophidae','Islas Canarias','Gran Canaria')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Fundulus heteroclitus','Fundulidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gymnothorax bacalladoi','Muraenidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Argentina sphyraena','Argentinidae','Peninsula','Madrid, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gobiidae','Gobiidae','Peninsula','Barcelona, Alicante, Castellón')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Thalassoma','Labridae','Peninsula','Valencia, Málaga, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Apogon imberbis','Apogonidae','Peninsula','Sevilla, Huelva, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scorpaena maderensis','Scorpaenidae','Peninsula','Málaga, Cádiz, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Canthigaster rostrata','Tetraodontidae','Peninsula','Alicante, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bothus podas','Bothidae','Peninsula','Cádiz, Huelva, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sparisoma cretense','Scaridae','Peninsula','Tarragona, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Mullus surmuletus','Mullidae','Peninsula','Baleares, Valencia, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Tripterygion delaisi','Tripterygiidae','Peninsula','Girona, Barcelona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Ophioblennius atlanticus','Blenniidae','Peninsula','Huelva, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Parablennius parvicornis','Blenniidae','Peninsula','Murcia, Alicante, Castellón')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Labrisomus cricota','Labrisomidae','Peninsula','Cádiz, Málaga, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Canthigaster','Tetraodontidae','Peninsula','Barcelona, Valencia, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lutjanidae','Lutjanidae','Peninsula','Valencia, Málaga, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Aphanius iberus','Cyprinodontidae','Peninsula','Madrid, Valencia, Castellón')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Valencia hispanica','Cyprinodontidae','Peninsula','Valencia, Alicante, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Salaria fluviatilis','Blenniidae','Peninsula','Castellón, Tarragona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gobiusculus flavescens','Gobiidae','Peninsula','Alicante, Málaga, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Coryphoblennius galerita','Blenniidae','Peninsula','Tarragona, Castellón, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sphoeroides spengleri','Tetraodontidae','Peninsula','Baleares, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Brama brama','Bramidae','Peninsula','Cádiz, Málaga, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Centroscymnus coelolepis','Somniosidae','Peninsula','Málaga, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Centrophorus granulosus','Centrophoridae','Peninsula','Barcelona, Valencia, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Etmopterus princeps','Etmopteridae','Peninsula','Sevilla, Cádiz, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Hydrolagus affinis','Chimaeridae','Peninsula','Valencia, Baleares, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Hexanchus griseus','Hexanchidae','Peninsula','Madrid, Cádiz, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Squalus megalops','Squalidae','Peninsula','Baleares, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Etmopterus spinax','Etmopteridae','Peninsula','Cádiz, Málaga, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Blennius parvicornis','Blenniidae','Peninsula','Girona, Barcelona, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Mauligobius maderensis','Gobiidae','Peninsula','Huelva, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplodus bellottii','Sparidae','Peninsula','Tarragona, Castellón, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Canthigaster capistrata','Tetraodontidae','Peninsula','Madrid, Valencia, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Liza ramada','Mugilidae','Peninsula','Barcelona, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scomber japonicus','Scombridae','Peninsula','Valencia, Alicante, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pseudupeneus prayensis','Mullidae','Peninsula','Sevilla, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphodus roissali','Labridae','Peninsula','Málaga, Cádiz, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Synodus synodus','Synodontidae','Peninsula','Alicante, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Labrisomus nuchipinnis','Labrisomidae','Peninsula','Cádiz, Huelva, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sphyraena sphyraena','Sphyraenidae','Peninsula','Tarragona, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplodus cervinus','Sparidae','Peninsula','Baleares, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Thalassoma pavo','Labridae','Peninsula','Girona, Barcelona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Kyphosus sectatrix','Kyphosidae','Peninsula','Huelva, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachurus trachurus','Carangidae','Peninsula','Castellón, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Serranus atricauda','Serranidae','Peninsula','La Rioja, Burgos, Salamanca')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pomatoschistus bathi','Gobiidae','Peninsula','Zamora, Salamanca, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphodus bailloni','Labridae','Peninsula','Ávila, Segovia, Madrid')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Tripterygion tripteronotus','Tripterygiidae','Peninsula','Toledo, Segovia, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Tripterygion melanurus','Tripterygiidae','Peninsula','Segovia, Madrid, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachinotus ovatus','Carangidae','Peninsula','Valladolid, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gobius bucchichi','Gobiidae','Peninsula','Madrid, Alicante, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphodus ocellatus','Labridae','Peninsula','Salamanca, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lithognathus mormyrus','Sparidae','Peninsula','Burgos, Castellón, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Oedalechilus labeo','Mugilidae','Peninsula','Córdoba, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphodus tinca','Labridae','Peninsula','Murcia, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Chromogobius britoi','Gobiidae','Peninsula','Alicante, Baleares, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachyrincus scabrus','Macrouridae','Peninsula','Valencia, Baleares, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Ophidion barbatum','Ophidiidae','Peninsula','Cáceres, Cádiz, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Chelidonichthys lastoviza','Triglidae','Peninsula','Segovia, Madrid, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Helicolenus dactylopterus','Scorpaenidae','Peninsula','Zaragoza, Cádiz, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Serranus scriba','Serranidae','Peninsula','Badajoz, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Serranus hepatus','Serranidae','Peninsula','Salamanca, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Blennius ocellaris','Blenniidae','Peninsula','Ciudad Real, Castellón, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagrus pagrus','Sparidae','Peninsula','Lugo, A Coruña, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Mullus barbatus','Mullidae','Peninsula','León, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Cepola macrophthalma','Cepolidae','Peninsula','Lugo, Asturias, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Uranoscopus scaber','Uranoscopidae','Peninsula','León, Barcelona, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachinus draco','Trachinidae','Peninsula','Valencia, Alicante, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachinus araneus','Trachinidae','Peninsula','Alicante, Valencia, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Muraena helena','Muraenidae','Peninsula','Málaga, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scorpaena ustulata','Scorpaenidae','Peninsula','Cádiz, Málaga, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scorpaena porcus','Scorpaenidae','Peninsula','Barcelona, Valencia, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Oblada melanura','Sparidae','Peninsula','Tarragona, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Parablennius gattorugine','Blenniidae','Peninsula','Girona, Tarragona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gobiidae','Gobiidae','Peninsula','Tarragona, Lugo, Gipuzkoa, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphodus scina','Labridae','Peninsula','Tarragona, Barcelona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Liza labeo','Mugilidae','Peninsula','Valencia, Tarragona, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Belone belone','Belonidae','Peninsula','Cádiz, Valencia, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplodus sargus','Sparidae','Peninsula','Alicante, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepadogaster candollei','Gobiesocidae','Peninsula','Cádiz, Huelva, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scorpaena notata','Scorpaenidae','Peninsula','Barcelona, Tarragona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Blennius zvonimiri','Blenniidae','Peninsula','Valencia, Alicante, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Parablennius rouxi','Blenniidae','Peninsula','Tarragona, Castellón, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lipophrys trigloides','Blenniidae','Peninsula','Huelva, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Fundulidae','Fundulidae','Peninsula','Cádiz, Huelva, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Microlipophrys dalmatinus','Blenniidae','Peninsula','Málaga, Cádiz, Baleares')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Microlipophrys canevae','Blenniidae','Peninsula','Girona, Valencia, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Hippocampus hippocampus','Syngnathidae','Peninsula','Cádiz, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pomatoschistus microps','Gobiidae','Peninsula','Valencia, Tarragona, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('Francia o España','Hippocampus','Syngnathidae','Peninsula','Girona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Fundulidae','Fundulidae','Peninsula','Huelva, Cádiz, Granada')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Antennarius nummifer','Antennariidae','Islas Canarias','La Gomera, El Hierro')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Neoraja iberica','Rajidae','Península','Valencia, Tarragona, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Triglidae','Triglidae','Península','Barcelona, Tarragona, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplodus annularis','Sparidae','Península','Alicante, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplodus vulgaris','Sparidae','Península','Valencia, Alicante, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gadidae','Gadidae','Península','Cantabria, Vizcaya')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sardina pilchardus','Clupeidae','Península','Cádiz, Málaga, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Raja clavata','Rajidae','Península','Valencia, Alicante, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scyliorhinus canicula','Scyliorhinidae','Península','Alicante, Cádiz, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sciaena aquila','Sciaenidae','Península','Málaga, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lophius','Lophiidae','Península','Barcelona, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Coris julis','Labridae','Península','Málaga, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Halobatrachus didactylus','Batrachoididae','Península','Alicante, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Plectorhinchus mediterraneus','Haemulidae','Península','Girona, Tarragona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Plectorhynchus','Haemulidae','Península','Valencia, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Dicentrarchus punctatus','Moronidae','Península','Cádiz, Málaga, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Anguilla anguilla','Anguillidae','Península','Huelva, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus erythrinus','Sparidae','Península','Valencia, Tarragona, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplodus puntazzo','Sparidae','Península','Alicante, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Citharus linguatula','Citharidae','Península','Tarragona, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachurus mediterraneus','Carangidae','Península','Barcelona, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sarda sarda','Scombridae','Península','Cádiz, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus acarne','Sparidae','Península','Girona, Tarragona, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Boops boops','Sparidae','Península','Valencia, Alicante, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sparidae','Sparidae','Península','A Coruña,Lugo,Pontevedra')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Merluccius merluccius','Merlucciidae','Península','Cádiz, Málaga, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scomber scombrus','Scombridae','Península','Barcelona, Tarragona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pomolobus','Clupeidae','Península','Valencia, Barcelona, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Chelon labrosus','Mugilidae','Península','Tarragona, Valencia, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Labrus','Labridae','Península','Huelva, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Belone svetovidovi','Belonidae','Península','Alicante, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Zeus faber','Zeidae','Península','Cádiz, Málaga, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Conger conger','Congridae','Península','Barcelona, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Dicentrarchus labrax','Moronidae','Península','Valencia, Cádiz, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sarpa salpa','Sparidae','Península','Málaga, Cádiz, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trisopterus luscus','Gadidae','Península','Girona, Tarragona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Tilapia','Cichlidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scomberomorus tritor','Scombridae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Psettodes bennettii','Psettodidae','Islas Canarias','Islas Canarias')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Brama raii','Bramidae','Península','Málaga,Almería')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Brama japonica','Bramidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Regalecus','Regalecidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Minyichthys sentus','Syngnathidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Cyclothone pallida','Gonostomatidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scopelarchus analis','Scopelarchidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stomias','Stomiidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Paralepididae','Paralepididae','Islas Canarias','-')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Benthosema glaciale','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Macroparalepis affine','Paralepididae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Macroparalepis brevis','Paralepididae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Conger','Congridae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Ceratoscopelus warmingii','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Margrethia obtusirostra','Gonostomatidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Paralepis','Paralepididae','Islas Canarias','-')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Conger conger','Congridae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Brama','Bramidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Benthosema suborbitale','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scopelarchus michaelsarsi','Scopelarchidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bathylagus longirostris','Bathylagidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lestidiops jayakari pseudosphyraenoides','Paralepididae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lestidiops jayakari jayakari','Paralepididae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Acropomatidae','Acropomatidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gigantactis','Gigantactinidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gonostoma denudatum','Gonostomatidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Ophichthidae','Ophichthidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scopelarchus','Scopelarchidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Paralepis atlantica','Paralepididae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lestidiops sphyraenoides','Paralepididae','Islas Canarias','-')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Nessorhamphus ingolfianus','Derichthyidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Alepisaurus','Alepisauridae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lestidiops affinis','Paralepididae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gnathophis','Congridae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sudis hyalina','Paralepididae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Cyclothone','Gonostomatidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampadena urophaos','Myctophidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Cyclothone','Gonostomatidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Anarchias euryurus','Muraenidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Arctozenus rissoi','Paralepididae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gonostoma elongatum','Gonostomatidae','Islas Canarias','Tenerife, La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Myctophum nitidulum','Myctophidae','Islas Canarias','Tenerife, Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplophos taenia','Gonostomatidae','Islas Canarias','La Palma, La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplospinus multistriatus','Gempylidae','Islas Canarias','Tenerife, La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampanyctus alatus','Myctophidae','Islas Canarias','La Palma, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampanyctus pusillus','Myctophidae','Peninsula','Cádiz, Málaga, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampadena urophaos atlantica','Myctophidae','Islas Canarias','Tenerife, La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Maurolicus amethystinopunctatus','Sternoptychidae','Peninsula','Valencia, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scopelosaurus argenteus','Notosudidae','Islas Canarias','Lanzarote, La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diaphus effulgens','Myctophidae','Islas Canarias','Tenerife, La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Taaningichthys bathyphilus','Myctophidae','Islas Canarias','Tenerife, Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Myctophum punctatum','Myctophidae','Peninsula','Girona, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Ceratoscopelus maderensis','Myctophidae','Islas Canarias','La Palma, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Benthodesmus','Trichiuridae','Islas Canarias','La Palma, Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepidophanes gaussi','Myctophidae','Islas Canarias','Tenerife, La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Notolychnus valdiviae','Myctophidae','Islas Canarias','La Palma, Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Valenciennellus tripunctulatus','Sternoptychidae','Islas Canarias','La Gomera, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diogenichthys atlanticus','Myctophidae','Islas Canarias','Lanzarote, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Nemichthys','Nemichthyidae','Islas Canarias','La Palma, La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Nemichthys scolopaceus','Nemichthyidae','Islas Canarias','Tenerife, La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampanyctus crocodilus','Myctophidae','Islas Canarias','La Palma, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diaphus mollis','Myctophidae','Islas Canarias','La Palma, Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diaphus rafinesquii','Myctophidae','Islas Canarias','La Palma, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Hygophum reinhardtii','Myctophidae','Islas Canarias','Lanzarote, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Ceratoscopelus maderensis','Myctophidae','Islas Canarias','La Palma, La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bolinichthys indicus','Myctophidae','Islas Canarias','Tenerife, La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Holtbyrnia','Platytroctidae','Islas Canarias','Lanzarote, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Foetorepus','Callionymidae','Islas Canarias','La Palma, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Hippocampus','Syngnathidae','Islas Canarias','Tenerife, Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Nannobrachium cuprarium','Myctophidae','Islas Canarias','La Palma, Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lobianchia gemellarii','Myctophidae','Islas Canarias','Tenerife, La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Nealotus tripes','Gempylidae','Islas Canarias','La Gomera, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lobianchia dofleini','Myctophidae','Islas Canarias','La Palma, Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampanyctus pusillus','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampanyctus festivus','Myctophidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Tetragonurus cuvieri','Tetragonuridae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampanyctus crocodilus','Myctophidae','Peninsula','Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gonichthys cocco','Myctophidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Nannobrachium lineatum','Myctophidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bonapartia pedaliota','Gonostomatidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Hygophum taaningi','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampanyctus photonotus','Myctophidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Notoscopelus resplendens','Myctophidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Notoscopelus bolini','Myctophidae','Peninsula','Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gempylus serpens','Gempylidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Myctophum selenops','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Argyropelecus','Sternoptychidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Manducus maderensis','Gonostomatidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Argyropelecus aculeatus','Sternoptychidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Cyclothone acclinidens','Gonostomatidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Melanonus zugmayeri','Melanonidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Hygophum hygomii','Myctophidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Centrobranchus nigroocellatus','Myctophidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stomias boa ferox','Stomiidae','Peninsula','Girona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Cyclothone braueri','Gonostomatidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Argyropelecus hemigymnus','Sternoptychidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Argyropelecus sladeni','Sternoptychidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stomias brevibarbatus','Stomiidae','Peninsula','Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Xenodermichthys copei','Alepocephalidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Canthigaster','Tetraodontidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bathylagus bericoides','Bathylagidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Capros aper','Caproidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stomias brevibarbatus','Stomiidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stomias boa boa','Stomiidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sternoptyx','Sternoptychidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Coryphaena equiselis','Coryphaenidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symbolophorus veranyi','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Macrouridae','Macrouridae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Myctophum punctatum','Myctophidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lampanyctus','Myctophidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepidophanes guentheri','Myctophidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bolinichthys','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diaphus brachycephalus','Myctophidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Linophryne','Linophrynidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Cyclothone pseudopallida','Gonostomatidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sudis atrox','Paralepididae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stomiidae','Trichiuridae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stomias boa','Stomiidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Argyropelecus hemigymnus','Sternoptychidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Nemichthys curvirostris','Nemichthyidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Opisthoproctus soleatus','Opisthoproctidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Spondyliosoma cantharus','Sparidae','Peninsula','Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Solea','Soleidae','Peninsula','Huelva, Cádiz, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Dasyatis centroura','Dasyatidae','Peninsula','Cádiz, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Paralepis coregonoides','Paralepididae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bothidae','Bothidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Soleidae','Soleidae','Peninsula','Cádiz, Huelva, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diaphus rafinesquii','Myctophidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diaphus holti','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Argentina','Argentinidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Crenilabrus bailloni','Labridae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sternoptyx diaphana','Sternoptychidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus bellottii','Sparidae','Peninsula','Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gonostoma denudatum','Gonostomatidae','Islas Canarias','La Gomera')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Serrivomer beanii','Serrivomeridae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diaphus holti','Myctophidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stomias boa boa','Stomiidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Tetragonuridae','Tetragonuridae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Beryx decadactylus','Berycidae','Peninsula','Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Melanocetus','Melanocetidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Callionymus reticulatus','Callionymidae','Peninsula','Cádiz, Málaga, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Mullidae','Mullidae','Peninsula','Valencia, Alicante, Barcelona, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sparidae','Sparidae','Peninsula','Barcelona, Valencia, Málaga, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Haemulidae','Haemulidae','Peninsula','Alicante, Valencia, Málaga, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Carangidae','Carangidae','Peninsula','Murcia, Alicante, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Clupeidae','Clupeidae','Peninsula','Huelva, Cádiz, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Serranidae','Serranidae','Peninsula','Málaga, Alicante, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scorpaena','Scorpaenidae','Peninsula','Valencia, Barcelona, Málaga, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pristipomoides','Lutjanidae','Peninsula','Cádiz, Barcelona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bothidae','Bothidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Soleidae','Soleidae','Peninsula','Cádiz, Málaga, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Uranoscopidae','Uranoscopidae','Peninsula','Tarragona, Barcelona, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus','Sparidae','Peninsula','Alicante, Valencia, Cádiz, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Kyphosidae','Kyphosidae','Peninsula','Valencia, Alicante, Cádiz, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Tetraodontidae','Tetraodontidae','Islas Canarias','Fuerteventura')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Hypsoblennius gentilis','Blenniidae','Peninsula','Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Xenomedea rhodopyga','Labrisomidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Malacoctenus hubbsi','Labrisomidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Enneanectes carminalis','Tripterygiidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Entomacrodus chiostictus','Blenniidae','Peninsula','Huelva, Cádiz, Málaga, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Thorogobius ephippiatus','Gobiidae','Peninsula','Cádiz, Barcelona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Epinephelus marginatus','Serranidae','Peninsula','Alicante, Málaga, Valencia, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gobius paganellus','Gobiidae','Peninsula','Barcelona, Tarragona, Valencia, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Scartella cristata','Blenniidae','Peninsula','Málaga, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Macroramphosus scolopax','Centriscidae','Peninsula','Valencia, Alicante, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Centrolabrus trutta','Labridae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepadogaster lepadogaster','Gobiesocidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Stephanolepis hispidus','Monacanthidae','Peninsula','Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Remora osteochir','Echeneidae','Peninsula','Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trachurus picturatus','Carangidae','Peninsula','Murcia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Synodus saurus','Synodontidae','Peninsula','Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lipophrys pavo','Blenniidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gobius auratus','Gobiidae','Peninsula','Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Syngnathus acus','Syngnathidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphodus cinereus','Labridae','Peninsula','Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Dicologoglossa cuneata','Soleidae','Peninsula','Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Syngnathus abaster','Syngnathidae','Islas Canarias','Lanzarote')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Trigla','Triglidae','Peninsula','Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Liza aurata','Mugilidae','Peninsula','Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Sparus auratus','Sparidae','Peninsula','Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Liza saliens','Mugilidae','Peninsula','Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Spicara maena','Emmelichthyidae','Peninsula','Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Blennius pavo','Blenniidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Merluccius merluccius','Gadidae','Peninsula','Asturias')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepidorhombus boscii','Bothidae','Peninsula','Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphodus rostratus','Labridae','Peninsula','Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Salaria pavo','Blenniidae','Islas Canarias','Tenerife')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Capros aper','Caproidae','Islas Canarias','La Palma')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Paralipophrys trigloides','Blenniidae','Peninsula','Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Tripterygion melanurus melanurus','Tripterygiidae','Balearic Islands','Ibiza')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Enneapterygius','Tripterygiidae','Peninsula','Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphurus insularis','Cynoglossidae','Balearic Islands','Majorca')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Coryphaena hippurus','Coryphaenidae','Balearic Islands','Majorca')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Salmo trutta','Salmonidae','Peninsula','Asturias, Cantabria, Galicia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Dentex maroccanus','Sparidae','Peninsula','Cádiz, Málaga, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Microchirus variegatus','Soleidae','Peninsula','Barcelona, Tarragona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Gobius','Gobiidae','Peninsula','Valencia, Alicante, Tarragona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pomatoschistus marmoratus','Gobiidae','Peninsula','Alicante, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Aphanius','Cyprinodontidae','Peninsula','Albacete, Cuenca, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lesueurigobius friesii','Gobiidae','Peninsula','Alicante, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Solea solea','Soleidae','Peninsula','Cádiz, Huelva, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Valencia lozanoi','Fundulidae','Peninsula','Valencia, Castellón')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Symphurus nigrescens','Cynoglossidae','Peninsula','Málaga, Cádiz, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Pagellus bogaraveo','Sparidae','Peninsula','Alicante, Valencia, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Zoarces anguillaris','Zoarcidae','Peninsula','Asturias, Cantabria, Galicia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Arnoglossus laterna','Bothidae','Peninsula','Huelva, Cádiz, Málaga')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Diplecogaster bimaculata','Gobiesocidae','Peninsula','Cádiz, Málaga, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Cyprinodontidae','Cyprinodontidae','Peninsula','Albacete, Valencia, Alicante')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Bodianus scrofa','Labridae','Peninsula','Cádiz, Valencia, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Anthias anthias','Serranidae','Peninsula','Barcelona, Tarragona, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Heteropriacanthus cruentatus','Priacanthidae','Peninsula','Málaga, Cádiz, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Polyacanthonotus rissoanus','Notacanthidae','Peninsula','Cádiz, Huelva, Barcelona')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Benthocometes robustus','Ophidiidae','Peninsula','Huelva, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepidorhombus whiffiagonis','Scophthalmidae','Peninsula','Cádiz, Málaga, Huelva')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepidorhombus boscii','Scophthalmidae','Peninsula','Málaga, Cádiz, Valencia')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Lepidopus caudatus','Trichiuridae','Peninsula','Alicante, Valencia, Cádiz')");
        sqLiteDatabase.execSQL("INSERT INTO peces VALUES ('España','Aphanopus carbo','Trichiuridae','Peninsula','Valencia, Barcelona, Cádiz')");



    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {
    }
}
